# Generated by Django 4.1.6 on 2023-02-19 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=140)),
                ('companyLink', models.URLField()),
                ('companyAddress', models.CharField(max_length=260)),
                ('companySize', models.IntegerField()),
                ('companyVacancy', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=600)),
                ('link', models.URLField()),
                ('salary', models.IntegerField()),
                ('experiences', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('deadline', models.DateTimeField()),
                ('skills', models.CharField(max_length=260)),
            ],
        ),
    ]
